# å¤œé—´æ¨¡å¼
mode: auto

# æ ‡è¯­è®¾ç½®
banner:
  enable: true
  title:
    - æœˆ
    - å…‰
    - å°
    - é•‡
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# å›¾æ ‡è®¾ç½®
# favicon: /favicon.ico
favicon: /favicon.jpg

# ä¸»é¢˜é¢œè‰²
#colors:
#  primary: "#F2BC57"
#  bg: "#F2F2F2"

# å¤´åƒè®¾ç½®
avatar:
  url: /favicon.jpg
  # url: /avatar.jpg
  status:
    enable: true
    emoji: ğŸŒ‘
    message: Looking for dawn.

# èƒŒæ™¯è®¾ç½®
bg_image:
  enable: true
  url: /bj.jpg
  # url: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-0-blur-30px.jpg
  # dark:
  # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

# æ‰“èµ
reward:
  enable: true
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±qwq
  methods:
    - name: æ”¯ä»˜å®
      # path: https://cdn.yunyoujun.cn/img/donate/alipay-qrcode.jpg
      path: https://off.cx/img/zfb.jpg
      color: '#00A3EE'
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      # path: https://cdn.yunyoujun.cn/img/donate/qqpay-qrcode.png
      path: https://off.cx/img/qq.png
      color: '#12B7F5'
      icon: ri:qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      # path: https://cdn.yunyoujun.cn/img/donate/wechatpay-qrcode.jpg
      path: https://off.cx/img/wx.png
      color: '#2DC100'
      icon: ri:wechat-pay-line

# ç‰ˆæƒ
creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

# ä»£ç é«˜äº®
codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow

# æ ‡ç­¾äº‘ï¼ˆè¯äº‘ï¼‰
wordcloud:
  enable: true
  height: 350

# Medium Zoom æ”¾å¤§é¢„è§ˆå›¾ç‰‡
# ç‚¹å‡»æ–‡ç« å›¾ç‰‡ï¼Œæ”¾å¤§é¢„è§ˆ
medium_zoom: true

# å…¨å±€éŸ³ä¹æ’­æ”¾å™¨
aplayer:
  global: true
  meting: false
  # https://github.com/metowolf/MetingJS/tree/v1.2#option
  widget:
    enable: true
    autoplay: false
    # theme: "#2980b9"
    loop: all
    order: list
    preload: auto
    volume: 0.7
    mutex: true
    lrcType: 0
    listFolded: true
    listMaxHeight: 340px
    audio:
      - name: æ˜ŸèŒ¶ä¼š
        artist: ç°æ¾ˆ
        url: https://nfy.dawnpe.com/music/%E6%98%9F%E8%8C%B6%E4%BC%9A.mp3
        cover: https://p3-sign.bdxiguaimg.com/tos-cn-i-0026/8eb02d4edcac460fbb3157351086bbd3~tplv-pk90l89vgd-crop-center:864:486.jpeg?x-expires=1692369361&x-signature=NdpbiymD8pOYoxdMtrHSTypV7OE%3D
      - name: ã„ã–ã€å‚ã‚Šã¾ã™
        artist: U-ske / æ£—ã„ã¤ã
        url: https://nfy.dawnpe.com/music/%E3%81%84%E3%81%96%E3%80%81%E5%8F%82%E3%82%8A%E3%81%BE%E3%81%99.m4a
        cover: https://s2.loli.net/2023/03/25/s8YOjBLaCQowMSX.jpg
      - name: é›ªé™ã‚Šã€ãƒ¡ãƒªã‚¯ãƒª(feat.Miku)
        artist: A-39 / æ²™åŒ…P / åˆéŸ³ãƒŸã‚¯
        url: https://nfy.dawnpe.com/music/%E9%9B%AA%E9%99%8D%E3%82%8A%E3%80%81%E3%83%A1%E3%83%AA%E3%82%AF%E3%83%AA(feat.Miku).m4a
        cover: https://s2.loli.net/2023/03/25/YKlAhBmEeig7uwT.jpg
    meting:
      enable: false
      id: 492390949
      server: netease
      type: playlist

# å†…å®¹å¡ç‰‡
post_card:
  opacity: 0.8

# å­—æ•°ç»Ÿè®¡
wordcount:
  enable: true
  count: true
  time: true

# å¯¼èˆª
menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: ä½ çŒœ
  custom:
    title: ç•™è¨€æ¿
    path: https://waline.off.cx/
    icon: ri:clipboard-line

# å…¬å‘Š
notice:
  enable: true
  content: Hey~ Welcome to my website! awa~<br>æœ€æ–°é€šçŸ¥ï¼š<br>æœ¬ç«™å·²äº2023å¹´2æœˆ19æ—¥æ›´æ¢Logoå¹¶æ”¹ç½‘åä¸ºâ€œæœˆå…‰å°é•‡â€ï¼ŒåŸå› æ˜¯ä¹‹å‰é‚£ä¸²è‹±æ–‡å¤ªå±‘äº†ï¼Œè¿˜ä¸å¦‚ç”¨ä¸­æ–‡ã€‚<br>æ–°Logoçš„æ•…äº‹ï¼š<br>å…³äºè¿™ä¸ªæ–°Logoï¼Œæ˜¯æˆ‘å¯’å‡åœ¨ç© Draw & Guess çš„æ—¶å€™ç”»å‹ä»¬ç”»çš„ï¼Œæ˜¯ä¸æ˜¯å¾ˆå¥½åº·[doge]ï¼Ÿ<br>å…³äºæˆ‘çš„ä¸€äº›æƒ…å†µï¼š<br>åˆä¸‰ä¸Šå­¦æœŸå·²ç»è¿‡å»äº†ï¼Œæ‰¬å·è¿™è¾¹ä¸­è€ƒåœ¨6æœˆ16æ—¥17æ—¥18æ—¥ä¸‰å¤©æ—¶é—´ï¼Œå¯èƒ½ä¸ä¼šé¢‘ç¹æ›´æ–°å•¦~ è¿˜è¯·å„ä½è§è°…ï¼<br><iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=1424964170&auto=0&height=66"></iframe><br>ä¸è¿‡æˆ‘ç›¸ä¿¡å…‰<br><iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=1461256747&auto=0&height=66"></iframe><!--<br>Hypixel Server</br> <br><iframe style="width:728px;height:90px;max-width:100%;border:none;display:block;margin:auto" src="https://namemc.com/server/mc.hypixel.net/embed" width="728" height="90"></iframe></br><br>æ¥ä¸ªå°å¹¿å‘Š(å›å›è¡€å•Š)</br><br><a href="https://evolution-host.com/" target="_blank" rel="nofollow noopener"><img src="https://img.dujin.org/images/evolution-host-328-82.png" alt="Invent the future with Evolution Host"></a></br>-->

# Chat
comment:
  candidates:
    - twikoo
    - waline
    # - livere
    # - giscus
    # - utterances
  tips:
    - æ¬¢è¿ç•™è¨€ï¼Œåšä¸»ä¸ä¼šæ¯å¤©éƒ½çœ‹è¯„è®ºï¼ˆ
    - è‹¥æ‚¨æƒ³åŠæ—¶å¾—åˆ°å›å¤æé†’ï¼Œå»ºè®®è·³è½¬ Twikoo è¯„è®ºã€‚

twikoo:
  enable: true
  envId: https://twikoo.off.cx # è…¾è®¯äº‘ç¯å¢ƒid
  region: ap-shanghai # ç¯å¢ƒåœ°åŸŸï¼Œé»˜è®¤ä¸º ap-shanghaiï¼Œå¦‚æœæ‚¨çš„ç¯å¢ƒåœ°åŸŸä¸æ˜¯ä¸Šæµ·ï¼Œéœ€ä¼ æ­¤å‚æ•°
  option: # ç”¨äºåŒºåˆ†ä¸åŒæ–‡ç« çš„è‡ªå®šä¹‰ js è·¯å¾„ï¼Œå¦‚æœæ‚¨çš„æ–‡ç« è·¯å¾„ä¸æ˜¯ location.pathnameï¼Œéœ€ä¼ æ­¤å‚æ•°

waline:
  enable: true
  serverURL: https://waline.off.cx/
  visitor: true
  comment: true
  emoji:
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/qq/
    - https://jsd.onmicrosoft.cn/npm/@waline/emojis@latest/tieba/
    - https://jsd.onmicrosoft.cn/gh/walinejs/emojis@latest/bmoji/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: [nick]
  
livere:
  enable: false
  uid: MTAyMC81NzY1Ny8zNDEyMA==

# https://github.com/laymonage/giscus
#giscus:
#  enable: true
#  repo: NiuFuyu855/HexoActions
#  repo-id: R_kgDOHe0j7Q
#  category: Blog Comment
#  category-id: DIC_kwDOHe0j7c4CRoYU
#  mapping: pathname
#  reactions-enabled: 1
#  emit-metadata: 0
#  theme: light

# https://utteranc.es/
#utterances:
#  enable: false
#  repo: NiuFuyu855/HexoActions
#  issue-term: pathname
#  # label: comment
#  theme: github-light

# é»˜å“€
mourn:
  enable: true
  days:
    - 4-4 # å…¨å›½å“€æ‚¼æ—¥ ä¸ºè¡¨è¾¾å…¨å›½å„æ—äººæ°‘å¯¹æŠ—å‡»æ–°å† è‚ºç‚ç–«æƒ…æ–—äº‰ç‰ºç‰²çƒˆå£«å’Œé€ä¸–åŒèƒçš„æ·±åˆ‡å“€æ‚¼ï¼Œå›½åŠ¡é™¢å†³å®šï¼Œ2020å¹´4æœˆ4æ—¥ä¸¾è¡Œå…¨å›½æ€§å“€æ‚¼æ´»åŠ¨ã€‚åœ¨æ­¤æœŸé—´ï¼Œå…¨å›½å’Œé©»å¤–ä½¿é¢†é¦†ä¸‹åŠæ——å¿—å“€ï¼Œå…¨å›½åœæ­¢å…¬å…±å¨±ä¹æ´»åŠ¨ã€‚4æœˆ4æ—¥10æ—¶èµ·ï¼Œå…¨å›½äººæ°‘é»˜å“€3åˆ†é’Ÿï¼Œæ±½è½¦ã€ç«è½¦ã€èˆ°èˆ¹é¸£ç¬›ï¼Œé˜²ç©ºè­¦æŠ¥é¸£å“ã€‚
    - 9-18 # ä¹ä¸€å…«äº‹å˜çºªå¿µæ—¥
    - 12-1 # 11-30 æ±Ÿæ³½æ°‘é€ä¸– é»˜å“€Day1
    - 12-2 # 11-30 æ±Ÿæ³½æ°‘é€ä¸– é»˜å“€Day2
    - 12-3 # 11-30 æ±Ÿæ³½æ°‘é€ä¸– é»˜å“€Day3
    - 12-4 # 11-30 æ±Ÿæ³½æ°‘é€ä¸– é»˜å“€Day4
    - 12-5 # 11-30 æ±Ÿæ³½æ°‘é€ä¸– é»˜å“€Day5
    - 12-6 # 11-30 æ±Ÿæ³½æ°‘é€ä¸– é»˜å“€Day6
    - 12-7 # 11-30 æ±Ÿæ³½æ°‘é€ä¸– é»˜å“€Day7
    - 12-13 # å—äº¬å¤§å± æ€æ­»éš¾è€…å›½å®¶å…¬ç¥­æ—¥

# Girls
girls:
  enable: true

# æœç´¢
algolia_search:
  enable: true
  hits:
    per_page: 10 # the number of search results per page

# æ–‡ç« è®¿å®¢ç»Ÿè®¡
leancloud_visitors:
  enable: true
  app_id: xtzijrHQv1rgIR3w9ukDbxJq-MdYXbMMI
  app_key: cVLuyWl93M6FHuHKy2hHNvmJ
  server_url: https://visit.api.off.cx

# head å¤´éƒ¨èµ„æº
head: 
  css: 
    waline: /css/waline-ua.css
    businesscardcss: /css/businesscard.css
    lantern: /css/lantern.css
  js: 
    base:  # å¿…é¡»æå‰åŠ è½½å¹¶æ‰§è¡Œã€‚
    async:  # å¼‚æ­¥åŠ è½½ï¼ŒåŠ è½½å®Œæˆåç«‹å³æ‰§è¡Œã€‚
    defer:  # å¼‚æ­¥åŠ è½½èµ„æºï¼Œä½†æœ€åæ‰§è¡Œã€‚
      businesscard: /js/businesscard.js
      loadbusinesscard: /js/load-businesscard.js

# é¡µè„š
footer:
  since: 2022
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²åœ¨é£é›¨ä¸­åšå¼ºåº¦è¿‡
    start_time: "2022-06-05 00:00:00"
  support:
    enable: true
    title: åˆæ‹äº‘
    link: https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral
    logo: https://s2.loli.net/2023/03/26/mBKX3SEZytqC6Qw.png
    prefix: æœ¬ç½‘ç«™ç”±
    suffix: æä¾› CDN åŠ é€Ÿä¸äº‘å­˜å‚¨æœåŠ¡
  custom_text: <a href="https://icp.gov.moe" target="_blank">èŒICPå¤‡</a><a href="https://icp.gov.moe/?keyword=20226111" target="_blank"> 20226111å·</a> <br><p></p>
    <br><font color="blue">
    ç«™ç‚¹è®¿é—®é‡ <span id="qexo-site-pv">Loading...</span>
    ç«™ç‚¹è®¿å®¢æ•° <span id="qexo-site-uv">Loading...</span>
    é¡µé¢è®¿é—®é‡ <span id="qexo-page-pv">Loading...</span>
    </font>
    <script src="https://cdn.jsdelivr.net/npm/qexo-static@1.3.0/hexo/statistic/statistic.min.js"></script>
    <script>
        loadStatistic("https://qexo.niufuyu.top")
    </script>
    <br><p></p><br><a href="https://travellings.cn/" target="_blank" rel="noopener" title="å¼€å¾€-å‹é“¾æ¥åŠ›"><img src="https://off.cx/img/travelling-logo.gif" alt="å¼€å¾€-å‹é“¾æ¥åŠ›" width="120"></a>
    <br>
    <br><a href="https://foreverblog.cn" target="_blank"><img height="25" alt="åå¹´ä¹‹çº¦" src="https://img.foreverblog.cn/logo_en_default.png"></a>
    <!-- 51.LAç»Ÿè®¡ -->
    <a target="_blank" title="51.LAç½‘ç«™ç»Ÿè®¡" href="https://v6.51.la/land/JpenND6UOGk9I9kD"><img src="https://s2.loli.net/2023/03/25/bWKGEs6in5e8Mhl.png"></a>
    <script charset="UTF-8" id="LA_COLLECT" src="//sdk.51.la/js-sdk-pro.min.js?id=JpenND6UOGk9I9kD&ck=JpenND6UOGk9I9kD&autoTrack=true&hashMode=true"></script>
    <script src="https://sdk.51.la/perf/js-sdk-perf.min.js" crossorigin="anonymous"></script>
    <script>new LingQue.Monitor().init({id:"JhF9yG6HEScPsZpm"});</script>
    <!-- å°¾å·´ -->
    <br><p><a style="margin-inline:5px" target="_blank" href="https://hexo.io/"><img src="https://img.shields.io/badge/Frame-Hexo-blue?style=flat&logo=hexo" title="åšå®¢æ¡†æ¶ä¸ºHexo"></a><a style="margin-inline:5px" target="_blank" href="https://hexo-theme-yun.vercel.app/"><img src="https://img.shields.io/badge/Theme-Yun-6513df?style=flat&logo=Google-Cloud" title="ä¸»é¢˜é‡‡ç”¨Yun"></a><a style="margin-inline:5px" target="_blank" href="https://www.jsdelivr.com/"><img src="https://img.shields.io/badge/CDN-jsDelivr-orange?style=flat&logo=jsDelivr" title="æœ¬ç«™ä½¿ç”¨JsDelivrä¸ºé™æ€èµ„æºæä¾›CDNåŠ é€Ÿ"></a><a style="margin-inline:5px" target="_blank" href="https://netlify.app/ "><img src="https://img.shields.io/badge/Hosted-Netlify-brightgreen?style=flat&logo=Netlify" title="æœ¬ç«™é‡‡ç”¨åŒçº¿éƒ¨ç½²ï¼Œé»˜è®¤çº¿è·¯æ‰˜ç®¡äºNetlify"></a><a style="margin-inline:5px" target="_blank" href="https://vercel.com/ "><img src="https://img.shields.io/badge/Hosted-Vercel-0cedbe?style=flat&logo=Vercel" title="æœ¬ç«™é‡‡ç”¨åŒçº¿éƒ¨ç½²ï¼Œå¤‡ç”¨çº¿è·¯æ‰˜ç®¡äºVercel"></a><a style="margin-inline:5px" target="_blank" href="https://github.com/NiuFuyu855/HexoActions"><img src="https://img.shields.io/badge/Source-Github-d021d6?style=flat&logo=GitHub" title="æœ¬ç«™é¡¹ç›®ç”±Githubæ‰˜ç®¡"></a><a style="margin-inline:5px" target="_blank" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://img.shields.io/badge/Copyright-BY--NC--SA%204.0-d42328?style=flat&logo=Claris" title="æœ¬ç«™é‡‡ç”¨çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº«4.0å›½é™…è®¸å¯åè®®è¿›è¡Œè®¸å¯"></a></p>
     
  beian:
    enable: true
    icp: è‹ICPå¤‡11451400å·

google_analytics:
  enable: false
  id: 

# ç¼–è¾‘æ–‡ç« 
post_edit:
  enable: true
  url: https://github.com/NiuFuyu855/HexoActions/tree/main/source/

# Tags
tags:
  å­¦ä¹ : saddlebrown
  æ•™ç¨‹: royalblue
  Minecraft: royalblue
  HMCL: royalblue
  Markdown: royalblue
  å…³äºæœ¬ç«™: royalblue
  å…³äºæˆ‘: royalblue
  å­¦ä¹ èµ„æ–™: royalblue
  Hello World: royalblue
  è„šæœ¬: royalblue
  ä»Šæ—¥çƒ­æ¦œ: red
  Outlook: royalblue
  æµ‹è¯•: green
  Demo: green
  Qexo: blue

# Categories
categories:
  æ—¥å¸¸: '#FB7299'
  æ¸¸æˆ: '#FB7299'
  Minecraft: '#FB7299'
  HMCL: '#FB7299'
  å…³äºæˆ‘: '#FB7299'
  Hello World: '#FB7299'
  å­¦ä¹ èµ„æ–™: '#FB7299'
  æ•™ç¨‹: '#FB7299'
  Markdown: '#FB7299'
  è„šæœ¬: '#FB7299'
  ä»Šæ—¥çƒ­æ¦œ: '#FB7299'
  æŠ€æœ¯åˆ†äº«: '#FB7299'
  æµ‹è¯•: '#FB7299'

# å†…å®¹å¡ç‰‡icon&color
types:
  link:
    color: blue
    icon: ri:external-link-line
  bilibili:
    color: '#FF8EB3'
    icon: ri:bilibili-line
  douban:
    color: '#007722'
    icon: ri:douban-line
  github:
    color: black
    icon: ri:github-line
  netease-cloud-music:
    color: '#C10D0C'
    icon: ri:netease-cloud-music-line
  notion:
    color: black
    icon: ri:notion
  twitter:
    color: '#1da1f2'
    icon: ri:twitter-line
  wechat:
    color: '#1AAD19'
    icon: ri:wechat-2-line
  weibo:
    color: '#E6162D'
    icon: ri:weibo-line
  yuque:
    color: '#25b864'
    icon: ri:yuque
  zhihu:
    color: '#0084FF'
    icon: ri:zhihu-line

# é¡µé¢
pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: ri:women-line
    color: pink
  - name: è¿½ç•ªåˆ—è¡¨
    url: /anime/
    icon: maki:cinema
    color: grey
  - name: è¿½å‰§åˆ—è¡¨
    url: /cinema/
    icon: maki:cinema
    color: grey
  - name: Steam Games
    url: /steamgames/
    icon: mdi:steam
    color: grey

# ScrollReveal
# é¦–é¡µå¡ç‰‡ä¸æ–‡ç« å†…éƒ¨å›¾ç‰‡çš„æ»šåŠ¨æµ®ç°æ•ˆæœ
scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

# Cursorå…‰æ ‡
cursor:
  enable: true

#ç™¾åº¦SEO
baidu_push: true
#GoogleSEO
google_tagmanager:
  enable: true
  id: GTM-KZV92F7

say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: false

social:
  - name: SiteMap
    link: /sitemap.xml
    icon: ri:rss-line
    color: blue
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
  #- name: QQ é¢‘é“ - å°äº‘ä¹‹å®¶
  #  # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
  #  link: https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&appChannel=share&inviteCode=28OEdR&appChannel=share&businessType=9&from=246610&biz=ka
  #  icon: ri:qq-line
  #  color: '#12B7F5'
  - name: GitHub
    link: https://github.com/NiuFuyu855
    icon: ri:github-line
    color: '#6e5494'
  - name: å¾®åš
    link: https://weibo.com/u/7752885949
    icon: ri:weibo-line
    color: '#E6162D'
  #- name: è±†ç“£
  #  link: https://www.douban.com/people/yunyoujun/
  #  icon: ri:douban-line
  #  color: '#007722'
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=2122329713
    icon: ri:netease-cloud-music-line
    color: '#C20C0C'
  #- name: çŸ¥ä¹
  #  link: javascript
  #  icon: ri:zhihu-line
  #  color: '#0084FF'
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/526873978
    icon: ri:bilibili-line
    color: '#FF8EB3'
  - name: Twitter
    link: https://twitter.com/NiuFuyu_CN
    icon: ri:twitter-line
    color: '#1da1f2'
  - name: Instagram
    link: https://www.instagram.com/niufuyu_cn/
    icon: ri:instagram-line
    color: '#FF8EB3'
  - name: FaceBook
    link: https://www.facebook.com/niufuyu
    icon: ri:facebook-circle-line
    color: blue
  - name: Reddit
    link: https://www.reddit.com/user/NiuFuyu
    icon: ri:reddit-line
    color: red
  - name: Twitch
    link: https://www.twitch.tv/nameflying_cn
    icon: ri:twitch-line
    color: purple
  - name: NameMC
    link: https://zh-cn.namemc.com/profile/NameFlying.1
    icon: mdi:minecraft
    color: green
  - name: Telegram Group
    link: https://t.me/LunarChat_CN
    icon: ri:telegram-line
    color: "#0088CC"
  - name: Telegram Channel
    link: https://t.me/LunarTownChannel
    # icon: ri:telegram-fill
    icon: ri:telegram-line
    color: '#0088CC'
  - name: Discord
    link: https://discord.gg/8nNJaBJc5G
    icon: ri:discord-line
    color: '#5A6DE2'
  - name: E-Mail
    link: mailto:me@off.cx
    icon: ri:mail-line
    color: '#8E71C1'
  - name: Talks
    link: /talks
    icon: ri:kakao-talk-line
    color: black
  - name: Travelling
    link: https://www.travellings.cn/go.html
    icon: ri:train-line
    color: black
pjax:
  enable: true
