# å¤œé—´æ¨¡å¼
mode: auto

# æ ‡è¯­è®¾ç½®
banner:
  enable: true
  title:
    - NIUTE
    - ã®
    - å±‘
    - ç ´
    - ç«™
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# å›¾æ ‡è®¾ç½®
# favicon: /favicon.ico
favicon: /favicon.jpg

# å¤´åƒè®¾ç½®
avatar:
  url: /avatar.jpg
  status:
    enable: true
    emoji: ğŸŒ‘
    message: Looking for dawn.

# èƒŒæ™¯è®¾ç½®
bg_image:
  enable: true
  url: /bj.jpg
  # url: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-0-blur-30px.jpg
  # dark:
  # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

# æ‰“èµ
reward:
  enable: true
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±qwq
  methods:
    - name: æ”¯ä»˜å®
      # path: https://cdn.yunyoujun.cn/img/donate/alipay-qrcode.jpg
      path: https://off.cx/img/zfb.jpg
      color: '#00A3EE'
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      # path: https://cdn.yunyoujun.cn/img/donate/qqpay-qrcode.png
      path: https://off.cx/img/qq.png
      color: '#12B7F5'
      icon: ri:qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      # path: https://cdn.yunyoujun.cn/img/donate/wechatpay-qrcode.jpg
      path: https://off.cx/img/wx.png
      color: '#2DC100'
      icon: ri:wechat-pay-line

# ç‰ˆæƒ
creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

# ä»£ç é«˜äº®
codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow

# Medium Zoom æ”¾å¤§é¢„è§ˆå›¾ç‰‡
# ç‚¹å‡»æ–‡ç« å›¾ç‰‡ï¼Œæ”¾å¤§é¢„è§ˆ
medium_zoom: true

# å…¨å±€éŸ³ä¹æ’­æ”¾å™¨
aplayer:
  global: true
  meting: false
  # https://github.com/metowolf/MetingJS/tree/v1.2#option
  widget:
    enable: true
    autoplay: false
    # theme: "#2980b9"
    loop: all
    order: list
    preload: auto
    volume: 0.7
    mutex: true
    lrcType: 0
    listFolded: true
    listMaxHeight: 340px
    audio:
      - name: æ˜ŸèŒ¶ä¼š
        artist: ç°æ¾ˆ
        url: https://cdn.jsdelivr.net/gh/NiuFuyu855/RandomMusic/æ˜ŸèŒ¶ä¼š.mp3
        cover: https://p3-sign.bdxiguaimg.com/tos-cn-i-0026/8eb02d4edcac460fbb3157351086bbd3~tplv-pk90l89vgd-crop-center:864:486.jpeg?x-expires=1692369361&x-signature=NdpbiymD8pOYoxdMtrHSTypV7OE%3D
    meting:
      enable: false
      id: 492390949
      server: netease
      type: playlist

# å†…å®¹å¡ç‰‡
post_card:
  opacity: 0.8

# å­—æ•°ç»Ÿè®¡
wordcount:
  enable: true
  count: true
  time: true

# å¯¼èˆª
menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: ä½ çŒœ
  custom:
    title: ç•™è¨€æ¿
    path: https://waline.niufuyu.top/
    icon: ri:clipboard-line

# å…¬å‘Š
notice:
  enable: true
  content: Hi. Welcome to my å±‘ç ´ç«™!qwq <br>åˆäºŒå·²ç»æµ‘æµ‘å™©å™©åœ°æ··è¿‡å»äº†ï¼ˆbushiï¼Œå·²ç»åˆä¸‰äº†ï¼Œå°†æ¥çš„ä¸€å¹´é‡Œå¯èƒ½ä¸ä¼šæ›´æ–°æ–‡ç« äº†ï¼ˆä½†ä¹Ÿä¸ä¸€å®šï¼‰ï¼Œè¦ä¸­è€ƒäº†qwq</br><br><iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=1424964170&auto=0&height=66"></iframe></br> <br>ä¸è¿‡æˆ‘ç›¸ä¿¡å…‰</br><br><iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=1461256747&auto=0&height=66"></iframe></br> <br>Hypixel Server</br> <br><iframe style="width:728px;height:90px;max-width:100%;border:none;display:block;margin:auto" src="https://namemc.com/server/mc.hypixel.net/embed" width="728" height="90"></iframe></br>

# waline
comment:
  candidates:
    - waline
    - giscus
  tips:
    - æ¬¢è¿ç•™è¨€ï¼Œåšä¸»ä¸ä¼šæ¯å¤©éƒ½çœ‹è¯„è®ºï¼ˆ

waline:
  enable: true
  serverURL: https://waline.off.cx/
  visitor: true
  comment: true
  emoji:
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: [nick]

# é»˜å“€
mourn:
  enable: true
  days:
    - 4-4
    - 9-18

# Girls
girls:
  enable: true

# æœç´¢
algolia_search:
  enable: true
  hits:
    per_page: 10 # the number of search results per page

# https://github.com/laymonage/giscus
giscus:
  enable: true
  repo: NiuFuyu855/HexoActions
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

# æ–‡ç« è®¿å®¢ç»Ÿè®¡
leancloud_visitors:
  enable: true
  app_id: xtzijrHQv1rgIR3w9ukDbxJq-MdYXbMMI
  app_key: cVLuyWl93M6FHuHKy2hHNvmJ
  server_url: https://xtzijrhq.api.lncldglobal.com

# headå¤´éƒ¨èµ„æº
#head: 
#  css: 
#  js: 

# é¡µè„š
footer:
  since: 2022
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²åœ¨é£é›¨ä¸­åšå¼ºåº¦è¿‡
    start_time: "2022-06-05 00:00:00"
  custom_text: <a href="https://icp.gov.moe" target="_blank">èŒICPå¤‡</a><a href="https://icp.gov.moe/?keyword=20226111" target="_blank"> 20226111å·</a> <br><p> </p></br>
    <br><font color="red">
    ç«™ç‚¹è®¿é—®é‡ <span id="qexo-site-pv">Loading...</span>
    ç«™ç‚¹è®¿å®¢æ•° <span id="qexo-site-uv">Loading...</span>
    é¡µé¢è®¿é—®é‡ <span id="qexo-page-pv">Loading...</span>
    </font>
    <script src="https://cdn.jsdelivr.net/npm/qexo-static@1.3.0/hexo/statistic/statistic.min.js"></script>
    <script>
        loadStatistic("https://qexo.niufuyu.top")
    </script>
    </br><br><p> </p></br> <br><a href="https://www.oscs1024.com/project/NiuFuyu855/HexoActions?ref=badge_small" alt="OSCS Status"><img src="https://www.oscs1024.com/platform/badge/NiuFuyu855/HexoActions.svg?size=small"/></a></br> <br><a href="https://travellings.cn/" target="_blank" rel="noopener" title="å¼€å¾€-å‹é“¾æ¥åŠ›"><img src="https://travellings.cn/assets/logo.gif" alt="å¼€å¾€-å‹é“¾æ¥åŠ›" width="120"></a></br>
    <br><p></p></br>
    <br><a href="https://www.west.cn/" target="_blank" style="top:13px" title="æœ¬ç«™ç”±è¥¿éƒ¨æ•°ç æä¾›åŸŸåæœåŠ¡"><img src="https://www.west.cn/images2016/logo.jpg" data-src="https://www.west.cn/images2016/logo.jpg" alt="è¥¿éƒ¨æ•°ç " height="30"> </a>
        <a href="https://www.cloudflare.com/" target="_blank" style="top:13px" title="æœ¬ç«™ç”±CloudFlareæä¾›åŸŸåæ‰˜ç®¡æœåŠ¡"><svg viewBox="0 0 105 36" role="img" height="30px" aria-hidden="true"><path fill="#000" d="M11.679 26.754h2.353v6.423h4.111v2.06H11.68v-8.483zM20.58 31.02v-.024c0-2.436 1.965-4.412 4.584-4.412 2.62 0 4.56 1.951 4.56 4.387v.025c0 2.436-1.965 4.41-4.584 4.41-2.618 0-4.56-1.95-4.56-4.386zm6.743 0v-.024c0-1.223-.885-2.291-2.183-2.291-1.285 0-2.147 1.042-2.147 2.266v.025c0 1.222.886 2.29 2.171 2.29 1.298 0 2.159-1.042 2.159-2.266zM32.604 31.517v-4.763h2.389v4.714c0 1.223.618 1.806 1.564 1.806.946 0 1.564-.557 1.564-1.745v-4.775h2.39v4.7c0 2.74-1.564 3.939-3.978 3.939s-3.93-1.223-3.93-3.878M44.112 26.755h3.274c3.032 0 4.79 1.744 4.79 4.192v.025c0 2.447-1.782 4.265-4.838 4.265h-3.226v-8.483zm3.31 6.397c1.408 0 2.34-.775 2.34-2.146v-.024c0-1.357-.932-2.145-2.34-2.145h-.958v4.316l.959-.001zM55.596 26.754h6.791v2.06h-4.438v1.442h4.014v1.951h-4.014v3.03h-2.353v-8.483zM65.661 26.754h2.353v6.423h4.111v2.06h-6.464v-8.483zM78.273 26.693h2.268l3.614 8.544h-2.522l-.62-1.515H77.74l-.606 1.515h-2.474l3.614-8.544zm2.062 5.2l-.946-2.413-.959 2.412h1.905zM87.186 26.754H91.2c1.298 0 2.195.34 2.765.921.498.485.752 1.14.752 1.976v.024c0 1.296-.693 2.156-1.746 2.605l2.025 2.957H92.28l-1.71-2.57h-1.03v2.57h-2.353v-8.483zm3.905 4.072c.8 0 1.262-.388 1.262-1.006v-.024c0-.667-.486-1.006-1.275-1.006h-1.54v2.038l1.553-.002zM98.112 26.754h6.827v2h-4.498v1.284h4.075v1.854h-4.075v1.346H105v1.999h-6.888v-8.483zM6.528 32.014c-.33.744-1.023 1.272-1.944 1.272-1.286 0-2.171-1.067-2.171-2.29v-.025c0-1.223.86-2.266 2.146-2.266.97 0 1.708.595 2.02 1.406h2.48c-.398-2.02-2.173-3.526-4.475-3.526-2.62 0-4.584 1.977-4.584 4.41v.024c0 2.436 1.94 4.388 4.56 4.388 2.24 0 3.991-1.45 4.453-3.393H6.528z"></path><path d="M89.012 22.355l.257-.887c.306-1.056.192-2.031-.321-2.748-.472-.66-1.259-1.049-2.214-1.094l-18.096-.229a.358.358 0 01-.285-.151.367.367 0 01-.04-.326.481.481 0 01.42-.321l18.263-.232c2.166-.099 4.512-1.856 5.333-3.998L93.37 9.65a.659.659 0 00.028-.36C92.216 3.975 87.468 0 81.792 0c-5.23 0-9.67 3.373-11.263 8.061a5.34 5.34 0 00-3.756-1.039 5.356 5.356 0 00-4.637 6.644c-4.099.12-7.386 3.475-7.386 7.6 0 .368.028.735.082 1.1a.354.354 0 00.348.305l33.408.004h.009a.44.44 0 00.415-.32z" fill="#F6821F"></path><path d="M95.04 9.847c-.167 0-.334.004-.5.013a.28.28 0 00-.079.017.285.285 0 00-.182.192l-.712 2.456c-.305 1.055-.192 2.03.322 2.746.471.661 1.258 1.05 2.213 1.094l3.858.232a.351.351 0 01.275.149.365.365 0 01.041.328.484.484 0 01-.42.32l-4.008.232c-2.176.1-4.521 1.856-5.342 3.998l-.29.756a.212.212 0 00.095.262c.03.017.062.027.096.028h13.802a.366.366 0 00.356-.265 9.846 9.846 0 00.367-2.677c-.001-5.457-4.429-9.88-9.891-9.88z" fill="#FBAD41"></path></svg> </a>
        <a href="https://vercel.com/" target="_blank" style="top:13px" title="æœ¬ç«™æ‰˜ç®¡åœ¨Vercel"><svg aria-label="Vercel Logotype" fill="var(--geist-foreground)" height="30px" viewBox="0 0 284 65"><path d="M141.68 16.25c-11.04 0-19 7.2-19 18s8.96 18 20 18c6.67 0 12.55-2.64 16.19-7.09l-7.65-4.42c-2.02 2.21-5.09 3.5-8.54 3.5-4.79 0-8.86-2.5-10.37-6.5h28.02c.22-1.12.35-2.28.35-3.5 0-10.79-7.96-17.99-19-17.99zm-9.46 14.5c1.25-3.99 4.67-6.5 9.45-6.5 4.79 0 8.21 2.51 9.45 6.5h-18.9zm117.14-14.5c-11.04 0-19 7.2-19 18s8.96 18 20 18c6.67 0 12.55-2.64 16.19-7.09l-7.65-4.42c-2.02 2.21-5.09 3.5-8.54 3.5-4.79 0-8.86-2.5-10.37-6.5h28.02c.22-1.12.35-2.28.35-3.5 0-10.79-7.96-17.99-19-17.99zm-9.45 14.5c1.25-3.99 4.67-6.5 9.45-6.5 4.79 0 8.21 2.51 9.45 6.5h-18.9zm-39.03 3.5c0 6 3.92 10 10 10 4.12 0 7.21-1.87 8.8-4.92l7.68 4.43c-3.18 5.3-9.14 8.49-16.48 8.49-11.05 0-19-7.2-19-18s7.96-18 19-18c7.34 0 13.29 3.19 16.48 8.49l-7.68 4.43c-1.59-3.05-4.68-4.92-8.8-4.92-6.07 0-10 4-10 10zm82.48-29v46h-9v-46h9zM37.59.25l36.95 64H.64l36.95-64zm92.38 5l-27.71 48-27.71-48h10.39l17.32 30 17.32-30h10.39zm58.91 12v9.69c-1-.29-2.06-.49-3.2-.49-5.81 0-10 4-10 10v14.8h-9v-34h9v9.2c0-5.08 5.91-9.2 13.2-9.2z"></path></svg> </a>
        <a href="https://github.com/NiuFuyu855" target="_blank" style="top:13px" title="æœ¬ç«™ä»£ç ç”±GitHubæä¾›ä»£ç æ‰˜ç®¡æœåŠ¡"><img src="https://off.cx/img/GitHub.png" data-src="https://off.cx/img/GitHub.png" alt="github" height="30"> </a>
        <a href="https://hexo.io/zh-cn/index.html" target="_blank" style="top:13px" title="æœ¬ç«™åŸºäºHexoæ¡†æ¶æ­å»º"><img src="https://off.cx/img/hexo.png" data-src="https://off.cx/img/hexo.png" alt="hexo" height="30"></a></br>
  beian:
    enable: true
    icp: æµ™ICPå¤‡13034790å·-3

google_analytics:
  enable: false
  id: 

# ç¼–è¾‘æ–‡ç« 
post_edit:
  enable: true
  url: https://github.com/NiuFuyu855/HexoActions/tree/main/source/

# Tags
tags:
  å­¦ä¹ : saddlebrown
  æ•™ç¨‹: royalblue
  Minecraft: royalblue
  HMCL: royalblue
  Markdown: royalblue
  å…³äºæœ¬ç«™: royalblue
  å…³äºæˆ‘: royalblue
  å­¦ä¹ èµ„æ–™: royalblue
  Hello World: royalblue
  è„šæœ¬: royalblue
  ä»Šæ—¥çƒ­æ¦œ: red
  Outlook: royalblue
  æµ‹è¯•: green
  Demo: green
  Qexo: blue

# Categories
categories:
  æ—¥å¸¸: '#FB7299'
  æ¸¸æˆ: '#FB7299'
  Minecraft: '#FB7299'
  HMCL: '#FB7299'
  å…³äºæˆ‘: '#FB7299'
  Hello World: '#FB7299'
  å­¦ä¹ èµ„æ–™: '#FB7299'
  æ•™ç¨‹: '#FB7299'
  Markdown: '#FB7299'
  è„šæœ¬: '#FB7299'
  ä»Šæ—¥çƒ­æ¦œ: '#FB7299'
  æŠ€æœ¯åˆ†äº«: '#FB7299'
  æµ‹è¯•: '#FB7299'

# å†…å®¹å¡ç‰‡icon&color
types:
  link:
    color: blue
    icon: ri:external-link-line
  bilibili:
    color: '#FF8EB3'
    icon: ri:bilibili-line
  douban:
    color: '#007722'
    icon: ri:douban-line
  github:
    color: black
    icon: ri:github-line
  netease-cloud-music:
    color: '#C10D0C'
    icon: ri:netease-cloud-music-line
  notion:
    color: black
    icon: ri:notion
  twitter:
    color: '#1da1f2'
    icon: ri:twitter-line
  wechat:
    color: '#1AAD19'
    icon: ri:wechat-2-line
  weibo:
    color: '#E6162D'
    icon: ri:weibo-line
  yuque:
    color: '#25b864'
    icon: ri:yuque
  zhihu:
    color: '#0084FF'
    icon: ri:zhihu-line

# é¡µé¢
pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: ri:women-line
    color: pink
  - name: è¿½ç•ªåˆ—è¡¨
    url: /anime/
    icon: maki:cinema
    color: grey
  - name: è¿½å‰§åˆ—è¡¨
    url: /cinema/
    icon: maki:cinema
    color: grey
  - name: Steam Games
    url: /steamgames/
    icon: mdi:steam
    color: grey

# ScrollReveal
# é¦–é¡µå¡ç‰‡ä¸æ–‡ç« å†…éƒ¨å›¾ç‰‡çš„æ»šåŠ¨æµ®ç°æ•ˆæœ
scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

# Cursorå…‰æ ‡
cursor:
  enable: true

#ç™¾åº¦SEO
baidu_push: true
#GoogleSEO
google_tagmanager:
  enable: true
  id: GTM-KZV92F7

say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: false

social:
  - name: SiteMap
    link: /sitemap.xml
    icon: ri:rss-line
    color: blue
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
  #- name: QQ é¢‘é“ - å°äº‘ä¹‹å®¶
  #  # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
  #  link: https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&appChannel=share&inviteCode=28OEdR&appChannel=share&businessType=9&from=246610&biz=ka
  #  icon: ri:qq-line
  #  color: '#12B7F5'
  - name: GitHub
    link: https://github.com/NiuFuyu855
    icon: ri:github-line
    color: '#6e5494'
  - name: å¾®åš
    link: https://weibo.com/u/7752885949
    icon: ri:weibo-line
    color: '#E6162D'
  #- name: è±†ç“£
  #  link: https://www.douban.com/people/yunyoujun/
  #  icon: ri:douban-line
  #  color: '#007722'
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=2122329713
    icon: ri:netease-cloud-music-line
    color: '#C20C0C'
  #- name: çŸ¥ä¹
  #  link: javascript
  #  icon: ri:zhihu-line
  #  color: '#0084FF'
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/526873978
    icon: ri:bilibili-line
    color: '#FF8EB3'
  - name: Twitter
    link: https://twitter.com/niufuyu123
    icon: ri:twitter-line
    color: '#1da1f2'
  # - name: Telegram
  #   link: https://t.me/yunyoujun_group
  #   icon: ri:telegram-line
  #   color: "#0088CC"
  - name: Telegram Channel
    link: https://t.me/+fniY9CTR8bphZDVl
    # icon: ri:telegram-fill
    icon: ri:telegram-line
    color: '#0088CC'
  #- name: Discord
  #  link: https://discord.gg/nd3mPkU5j8
  #  icon: ri:discord-line
  #  color: '#5A6DE2'
  - name: E-Mail
    link: mailto:me@off.cx
    icon: ri:mail-line
    color: '#8E71C1'
  - name: Travelling
    link: https://travellings.cn
    icon: ri:train-line
    color: black
pjax:
  enable: true