# å¤œé—´æ¨¡å¼
mode: auto

# æ ‡è¯­è®¾ç½®
banner:
  enable: true
  title:
    - NIUTE
    - ã®
    - å±‘
    - ç ´
    - ç«™
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# å›¾æ ‡è®¾ç½®
# favicon: /favicon.ico
favicon: /favicon.jpg

# å¤´åƒè®¾ç½®
avatar:
  url: /avatar.jpg
  status:
    enable: true
    emoji: ğŸŒ‘
    message: Looking for dawn.

# èƒŒæ™¯è®¾ç½®
bg_image:
  enable: true
  url: /bj.jpg
  # url: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-0-blur-30px.jpg
  # dark:
  # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

# æ‰“èµ
reward:
  enable: true
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±qwq
  methods:
    - name: æ”¯ä»˜å®
      # path: https://cdn.yunyoujun.cn/img/donate/alipay-qrcode.jpg
      path: https://img-niufuyu.vercel.app/Onedrive/zfb.jpg
      color: '#00A3EE'
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      # path: https://cdn.yunyoujun.cn/img/donate/qqpay-qrcode.png
      path: https://img-niufuyu.vercel.app/Onedrive/qq.png
      color: '#12B7F5'
      icon: ri:qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      # path: https://cdn.yunyoujun.cn/img/donate/wechatpay-qrcode.jpg
      path: https://img-niufuyu.vercel.app/Onedrive/wx.png
      color: '#2DC100'
      icon: ri:wechat-pay-line

# ç‰ˆæƒ
creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

# ä»£ç é«˜äº®
codeblock:
  copy_btn: true

# Medium Zoom æ”¾å¤§é¢„è§ˆå›¾ç‰‡
# ç‚¹å‡»æ–‡ç« å›¾ç‰‡ï¼Œæ”¾å¤§é¢„è§ˆ
medium_zoom: true

# å­—æ•°ç»Ÿè®¡
wordcount:
  enable: true
  count: true
  time: true

# å¯¼èˆª
menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: ä½ çŒœ
  custom:
    title: ç•™è¨€æ¿
    path: https://waline.niufuyu.top/
    icon: ri:clipboard-line

# å…¬å‘Š
notice:
  enable: true
  content: Hi. Welcome to my å±‘ç ´ç«™!qwq <br>ä¼šè€ƒç»“æŸäº†ï¼Œå·²ç»å‡†åˆä¸‰äº†ï¼Œå°†æ¥çš„ä¸€å¹´é‡Œå¯èƒ½ä¸ä¼šæ›´æ–°æ–‡ç« äº†ï¼Œè¦ä¸­è€ƒäº†qwq</br><br><iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=1424964170&auto=0&height=66"></iframe></br> <br>ä¸è¿‡æˆ‘ç›¸ä¿¡å…‰</br><br><iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=1461256747&auto=0&height=66"></iframe></br> <br>Hypixel Server</br> <br><iframe style="width:728px;height:90px;max-width:100%;border:none;display:block;margin:auto" src="https://namemc.com/server/mc.hypixel.net/embed" width="728" height="90"></iframe></br>

# waline
comment:
  candidates:
    - waline
    # - giscus
  tips:
    - æ¬¢è¿ç•™è¨€ï¼Œåšä¸»ä¸ä¼šæ¯å¤©éƒ½çœ‹è¯„è®ºï¼ˆ

waline:
  enable: true
  serverURL: https://waline.niufuyu.top/
  visitor: true
  comment: true
  emoji:
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: [nick]

# é»˜å“€
mourn:
  enable: true
  days:
    - 4-4

# Girls
girls:
  enable: true

# æœç´¢
algolia_search:
  enable: true
  hits:
    per_page: 10 # the number of search results per page

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: NiuFuyu855/NiuFuyu855.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

# æ–‡ç« è®¿å®¢ç»Ÿè®¡
leancloud_visitors:
  enable: true
  app_id: xtzijrHQv1rgIR3w9ukDbxJq-MdYXbMMI
  app_key: cVLuyWl93M6FHuHKy2hHNvmJ
  server_url: https://xtzijrhq.api.lncldglobal.com

# é¡µè„š
footer:
  since: 2022
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²åœ¨é£é›¨ä¸­åšå¼ºåº¦è¿‡
    start_time: "2022-06-05 00:00:00"
  custom_text: <a href="https://icp.gov.moe" target="_blank">èŒICPå¤‡</a><a href="https://icp.gov.moe/?keyword=20226111" target="_blank"> 20226111å·</a> <br><p> </p></br> <br><a href="https://www.oscs1024.com/project/NiuFuyu855/HexoActions?ref=badge_small" alt="OSCS Status"><img src="https://www.oscs1024.com/platform/badge/NiuFuyu855/HexoActions.svg?size=small"/></a><br> <br><a href="https://travellings.link/" target="_blank" rel="noopener" title="å¼€å¾€-å‹é“¾æ¥åŠ›"><img src="https://travellings.link/assets/logo.gif" alt="å¼€å¾€-å‹é“¾æ¥åŠ›" width="120"></a> <br> </br> <br> </br>
    <br>
    ç«™ç‚¹è®¿é—®é‡ <span id="qexo-site-pv">Loading...</span>
    ç«™ç‚¹è®¿å®¢æ•° <span id="qexo-site-uv">Loading...</span>
    é¡µé¢è®¿é—®é‡ <span id="qexo-page-pv">Loading...</span>
    <script src="https://cdn.jsdelivr.net/npm/qexo-static@1.3.0/hexo/statistic/statistic.min.js"></script>
    <script>
        loadStatistic("https://qexo.niufuyu.top")
    </script>
    </br>
  beian:
    enable: false
    icp: 

google_analytics:
  enable: false
  id: 

# ç¼–è¾‘æ–‡ç« 
post_edit:
  enable: true
  url: https://github.com/NiuFuyu855/HexoActions/tree/main/source/

# Tags
tags:
  å­¦ä¹ : saddlebrown
  æ•™ç¨‹: royalblue
  Minecraft: royalblue
  HMCL: royalblue
  Markdown: royalblue
  å…³äºæœ¬ç«™: royalblue
  å…³äºæˆ‘: royalblue
  å­¦ä¹ èµ„æ–™: royalblue
  Hello World: royalblue
  è„šæœ¬: royalblue
  ä»Šæ—¥çƒ­æ¦œ: red
  Outlook: royalblue
  æµ‹è¯•: green
  Demo: green

# Categories
categories:
  æ—¥å¸¸: '#FB7299'
  æ¸¸æˆ: '#FB7299'
  Minecraft: '#FB7299'
  HMCL: '#FB7299'
  å…³äºæˆ‘: '#FB7299'
  Hello World: '#FB7299'
  å­¦ä¹ èµ„æ–™: '#FB7299'
  æ•™ç¨‹: '#FB7299'
  Markdown: '#FB7299'
  è„šæœ¬: '#FB7299'
  ä»Šæ—¥çƒ­æ¦œ: '#FB7299'
  æŠ€æœ¯åˆ†äº«: '#FB7299'
  æµ‹è¯•: '#FB7299'

# é¡µé¢
pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: ri:women-line
    color: pink
  - name: è¿½ç•ªåˆ—è¡¨
    url: /anime/
    icon: maki:cinema
    color: grey
  - name: è¿½å‰§åˆ—è¡¨
    url: /cinema/
    icon: maki:cinema
    color: grey
  - name: Steam Games
    url: /steamgames/
    icon: mdi:steam
    color: grey

# ScrollReveal
# é¦–é¡µå¡ç‰‡ä¸æ–‡ç« å†…éƒ¨å›¾ç‰‡çš„æ»šåŠ¨æµ®ç°æ•ˆæœ
scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

# Cursorå…‰æ ‡
cursor:
  enable: true

#ç™¾åº¦SEO
baidu_push: true
#GoogleSEO
google_tagmanager:
  enable: false
  id: 

say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: false

social:
  - name: SiteMap
    link: /sitemap.xml
    icon: ri:rss-line
    color: blue
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
  #- name: QQ é¢‘é“ - å°äº‘ä¹‹å®¶
  #  # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
  #  link: https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&appChannel=share&inviteCode=28OEdR&appChannel=share&businessType=9&from=246610&biz=ka
  #  icon: ri:qq-line
  #  color: '#12B7F5'
  - name: GitHub
    link: https://github.com/NiuFuyu855
    icon: ri:github-line
    color: '#6e5494'
  - name: å¾®åš
    link: https://weibo.com/u/7752885949
    icon: ri:weibo-line
    color: '#E6162D'
  #- name: è±†ç“£
  #  link: https://www.douban.com/people/yunyoujun/
  #  icon: ri:douban-line
  #  color: '#007722'
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=2122329713
    icon: ri:netease-cloud-music-line
    color: '#C20C0C'
  #- name: çŸ¥ä¹
  #  link: javascript
  #  icon: ri:zhihu-line
  #  color: '#0084FF'
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/526873978
    icon: ri:bilibili-line
    color: '#FF8EB3'
  - name: Twitter
    link: https://twitter.com/niufuyu123
    icon: ri:twitter-line
    color: '#1da1f2'
  # - name: Telegram
  #   link: https://t.me/yunyoujun_group
  #   icon: ri:telegram-line
  #   color: "#0088CC"
  - name: Telegram Channel
    link: https://t.me/+fniY9CTR8bphZDVl
    # icon: ri:telegram-fill
    icon: ri:telegram-line
    color: '#0088CC'
  #- name: Discord
  #  link: https://discord.gg/nd3mPkU5j8
  #  icon: ri:discord-line
  #  color: '#5A6DE2'
  - name: E-Mail
    link: mailto:me@wssb.ml
    icon: ri:mail-line
    color: '#8E71C1'
  - name: Travelling
    link: https://travellings.link
    icon: ri:train-line
    color: black
pjax:
  enable: true